User.create({name: 'Ethan Lam', email: "etham.lam@examplesite.com", password: 'ripbrody2007'})
User.create({name: "Crystal Watts", email: "princess.crystal.869@examplesite.com", password: 'TiaraTime24142'})
User.create({name: 'Jason Sanchez', email: "jsan.villanueva@examplesite.com", password: "navyelite97002"})
User.create({name: "Kim Cheung", email: "cheung.kim@examplesite.com", password: "Ut45GsjhdhlU242"})
User.create({name: "Tiffany Wright", email: 't.r.wright@examplesite.com', password: "teeteehouse1*23"})
